services:
  mongo:
    image: mongo
    container_name: traffic_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: traffic_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/Capstone
      - JWT_SECRET=supersecretkey
      - SMTP_USER=himadribahuguna8@gmail.com
      - SMTP_PASS=yifjnhwkhnucctzm
      - BASE_URL=http://localhost:5000

  frontend:
    build: ./frontend
    container_name: traffic_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data: