Plotter_settings:
  Output: 'output/plots'
  Width: 1920
  Height: 1080
  Metrics:
    - system_total_stopped
    - system_total_waiting_time
    - system_mean_waiting_time
    - system_mean_speed

Agent_settings:
  Output_csv:   'output/csv'
  Output_model: 'output/models'

  Environment:
    Traffic_type: 'low'
    Gui:          False
    Num_seconds:  3600
    Min_green:    10
    Max_green:    50
    Yellow_time:  4
    Delta_time:   5

  Instances:

    Fixed_Low:
      Agent_type: 'FIXED'
      Runs: 1

    QL_Low:
      Agent_type: 'QL'
      Runs: 3
      Alpha:        0.1
      Gamma:        0.99
      Init_epsilon: 1.0
      Min_epsilon:  0.05
      Decay:        0.995

    DQN_Low:
      Agent_type: 'DQN'
      Runs: 2
      Alpha:        0.0005
      Gamma:        0.99
      Init_epsilon: 1.0
      Final_epsilon: 0.05
      Exp_fraction:  0.3
